# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-20 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
