# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0003_inspector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='Email template'),
        ),
    ]
