# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0004_alarm_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='template',
        ),
        migrations.AddField(
            model_name='alarm',
            name='html_template',
            field=models.TextField(blank=True, null=True, verbose_name='Email template (html)'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='subject',
            field=models.CharField(default=b'Subject', max_length=200),
        ),
        migrations.AddField(
            model_name='alarm',
            name='text_template',
            field=models.TextField(blank=True, null=True, verbose_name='Email template (text)'),
        ),
    ]
