# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0005_auto_20210121_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='salutation',
            field=models.CharField(default=b'Dear', max_length=100),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='html_template',
            field=models.TextField(blank=True, null=True, verbose_name='Html template'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='subject',
            field=models.CharField(default=b'Onderwerp', max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='text_template',
            field=models.TextField(blank=True, null=True, verbose_name='Text template'),
        ),
    ]
