# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0006_auto_20210121_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
