# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0007_alarm_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='html_template',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='text_template',
        ),
        migrations.AddField(
            model_name='alarm',
            name='message_text',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='subject',
            field=models.CharField(default='subject', max_length=200, verbose_name='subject'),
        ),
    ]
