# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-25 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0008_auto_20210123_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='Recipient',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='receivers',
            new_name='recipients',
        ),
    ]
