# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0009_auto_20210126_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('sent', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='delft.Event')),
                ('recipients', models.ManyToManyField(to='delft.Recipient')),
            ],
        ),
    ]
