# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='sent',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Subject', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='messages', to='delft.Recipient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
